/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./../components/ui/badge/Badge.vue')['default']
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Card: typeof import('./../components/ui/card/Card.vue')['default']
    CardContent: typeof import('./../components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../components/ui/card/CardTitle.vue')['default']
    Color: typeof import('./../components/Color.vue')['default']
    copy: typeof import('./../components/Red copy.vue')['default']
    Custom: typeof import('./../components/Custom.vue')['default']
    Default: typeof import('./../components/Default.vue')['default']
    Gray: typeof import('./../components/Gray.vue')['default']
    Image: typeof import('./../components/Image.vue')['default']
    Image1: typeof import('./../components/Image1.vue')['default']
    Image2: typeof import('./../components/Image2.vue')['default']
    Orange: typeof import('./../components/Orange.vue')['default']
    Red: typeof import('./../components/Red.vue')['default']
    ResizableHandle: typeof import('./../components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./../components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./../components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./../components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./../components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./../components/ui/tabs/TabsTrigger.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
  }
}
